# Generated by Django 4.0 on 2022-01-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='madan',
            old_name='country',
            new_name='payment',
        ),
        migrations.RenameField(
            model_name='madan',
            old_name='location',
            new_name='village',
        ),
        migrations.RemoveField(
            model_name='madan',
            name='state',
        ),
        migrations.AddField(
            model_name='madan',
            name='location_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='madan',
            name='shomareh_mojavez_kashf',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='madan',
            name='shomareh_parvaneh_bahrevardari',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='madan',
            name='tonazh_bahrebardari',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
